# Minimal world currency dataset (common + major). Add more as needed.

CURRENCIES = [
    {"code": "USD", "names": ["us dollar", "u.s. dollar", "dollar", "america", "united states"], "country": ["united states", "usa", "u.s."]},
    {"code": "EUR", "names": ["euro"], "country": ["eurozone", "europe"]},
    {"code": "GBP", "names": ["pound", "pound sterling", "british pound"], "country": ["united kingdom", "uk", "britain", "england"]},
    {"code": "INR", "names": ["rupee", "indian rupee"], "country": ["india"]},
    {"code": "PKR", "names": ["pakistani rupee", "rupee"], "country": ["pakistan", "pk"]},
    {"code": "JPY", "names": ["yen", "japanese yen"], "country": ["japan"]},
    {"code": "CNY", "names": ["yuan", "renminbi", "chinese yuan"], "country": ["china"]},
    {"code": "AUD", "names": ["australian dollar"], "country": ["australia"]},
    {"code": "CAD", "names": ["canadian dollar"], "country": ["canada"]},
    {"code": "CHF", "names": ["swiss franc", "franc"], "country": ["switzerland"]},
    {"code": "NZD", "names": ["new zealand dollar"], "country": ["new zealand"]},
    {"code": "SEK", "names": ["swedish krona", "krona"], "country": ["sweden"]},
    {"code": "NOK", "names": ["norwegian krone", "krone"], "country": ["norway"]},
    {"code": "DKK", "names": ["danish krone", "krone"], "country": ["denmark"]},
    {"code": "SGD", "names": ["singapore dollar"], "country": ["singapore"]},
    {"code": "HKD", "names": ["hong kong dollar"], "country": ["hong kong"]},
    {"code": "ZAR", "names": ["south african rand", "rand"], "country": ["south africa"]},
    {"code": "BRL", "names": ["brazilian real", "real"], "country": ["brazil"]},
    {"code": "MXN", "names": ["mexican peso", "peso"], "country": ["mexico"]},
    {"code": "TRY", "names": ["turkish lira", "lira"], "country": ["turkiye", "turkey"]},
    {"code": "AED", "names": ["u.a.e. dirham", "dirham"], "country": ["united arab emirates", "uae"]},
    {"code": "SAR", "names": ["saudi riyal", "riyal"], "country": ["saudi arabia"]},
    {"code": "QAR", "names": ["qatari riyal", "riyal"], "country": ["qatar"]},
    {"code": "KWD", "names": ["kuwaiti dinar", "dinar"], "country": ["kuwait"]},
    {"code": "BHD", "names": ["bahraini dinar", "dinar"], "country": ["bahrain"]},
    {"code": "OMR", "names": ["omani rial", "rial"], "country": ["oman"]},
    {"code": "EGP", "names": ["egyptian pound", "pound"], "country": ["egypt"]},
    {"code": "BDT", "names": ["taka", "bangladeshi taka"], "country": ["bangladesh"]},
    {"code": "LKR", "names": ["sri lankan rupee", "rupee"], "country": ["sri lanka"]},
    {"code": "NPR", "names": ["nepalese rupee", "rupee"], "country": ["nepal"]},
    {"code": "THB", "names": ["baht", "thai baht"], "country": ["thailand"]},
    {"code": "IDR", "names": ["rupiah", "indonesian rupiah"], "country": ["indonesia"]},
    {"code": "PHP", "names": ["philippine peso", "peso"], "country": ["philippines"]},
    {"code": "MYR", "names": ["malaysian ringgit", "ringgit"], "country": ["malaysia"]},
    {"code": "KRW", "names": ["won", "south korean won"], "country": ["south korea", "korea"]},
    {"code": "TWD", "names": ["new taiwan dollar"], "country": ["taiwan"]},
    {"code": "PLN", "names": ["zloty", "polish zloty"], "country": ["poland"]},
    {"code": "CZK", "names": ["czech koruna", "koruna"], "country": ["czechia", "czech republic"]},
    {"code": "HUF", "names": ["forint", "hungarian forint"], "country": ["hungary"]},
    {"code": "ILS", "names": ["shekel", "israeli new shekel"], "country": ["israel"]},
    {"code": "RUB", "names": ["ruble", "russian ruble"], "country": ["russia"]},
    {"code": "ARS", "names": ["argentine peso", "peso"], "country": ["argentina"]},
    {"code": "CLP", "names": ["chilean peso", "peso"], "country": ["chile"]},
    {"code": "COP", "names": ["colombian peso", "peso"], "country": ["colombia"]},
    {"code": "PEN", "names": ["sol", "peruvian sol"], "country": ["peru"]},
    {"code": "NGN", "names": ["naira", "nigerian naira"], "country": ["nigeria"]},
]


